module.exports = {
    talismans: {
        'FARMING_TALISMAN': 'Farming Talisman',
        'VACCINE_TALISMAN': 'Vaccine Talisman',
        'SPEED_TALISMAN': 'Speed Talisman',
        'WOOD_TALISMAN': 'Wood Affinity Talisman',
        'SKELETON_TALISMAN': 'Skeleton Talisman',
        'COIN_TALISMAN': 'Talisman of Coins',
        'MAGNETIC_TALISMAN': 'Magnetic Talisman',
        'GRAVITY_TALISMAN': 'Gravity Talisman', 
        'VILLAGE_TALISMAN': 'Village Affinity Talisman',
        'MINE_TALISMAN': 'Mine Affinity Talisman',
        'NIGHT_VISION_CHARM': 'Night Vision Charm',
        'LAVA_TALISMAN': 'Lava Talisman',
        'SCAVENGER_TALISMAN': 'Scavenger Talisman', 
        'WOLF_PAW': 'Wolf Paw',
        'FIRE_TALISMAN': 'Fire Talisman',    
        'BROKEN_PIGGY_BANK': 'Broken Piggy Bank',
        'CRACKED_PIGGY_BANK': 'Cracked Piggy Bank',
        'PIGGY_BANK': 'Piggy Bank',
        'PIGS_FOOT': 'Pig\'s Foot', 
        'FROZEN_CHICKEN': 'Frozen Chicken',
        'FISH_AFFINITY_TALISMAN': 'Fish Affinity Talisman',
        'FARMER_ORB': 'Farmer Orb',
        'HASTE_RING': 'Haste Ring',
        'NEW_YEAR_CAKE_BAG': 'New Year Cake Bag',
        'NIGHT_CRYSTAL': 'Night Crystal', 
        'DAY_CRYSTAL': 'Day Crystal',
        'FEATHER_ARTIFACT': 'Feather Artifact',
        'ARTIFACT_POTION_AFFINITY': 'Potion Affinity Artifact',
        'HEALING_RING': 'Healing Ring', 
        'CANDY_ARTIFACT': 'Candy Artifact',
        'EXPERIENCE_ARTIFACT': 'Experience Artifact',
        'MELODY_HAIR': '♪ Melody\'s Hair ♪',
        'SEA_CREATURE_ARTIFACT': 'Sea Creature Artifact',
        'INTIMIDATION_ARTIFACT': 'Intimidation Artifact',
        'WOLF_RING': 'Wolf Ring',
        'BAT_ARTIFACT': 'Bat Artifact',
        'DEVOUR_RING': 'Devour Ring',
        'ZOMBIE_ARTIFACT': 'Zombie Artifact',
        'SPIDER_ARTIFACT': 'Spider Artifact',
        'ENDER_ARTIFACT': 'Ender Artifact',
        'TARANTULA_TALISMAN': 'Tarantula Talisman',
        'SURVIVOR_CUBE': 'Survivor Cube',
        'WITHER_ARTIFACT': 'Wither Artifact',
        'WEDDING_RING_9': 'Legendary Ring of Love',
        'RED_CLAW_ARTIFACT': 'Red Claw Artifact',
        'BAIT_RING': 'Bait Ring',
        'SEAL_OF_THE_FAMILY': 'Seal of the Family',
        'HUNTER_RING': 'Hunter Ring',
    },

    tiered_talisman: {
        ARTIFACT_POTION_AFFINITY: ['POTION_AFFINITY_TALISMAN', 'RING_POTION_AFFINITY'],
        FEATHER_ARTIFACT: ['FEATHER_TALISMAN', 'FEATHER_RING'],
        SEA_CREATURE_ARTIFACT: ['SEA_CREATURE_TALISMAN', 'SEA_CREATURE_RING'],
        HEALING_RING: ['HEALING_TALISMAN'],
        CANDY_ARTIFACT: ['CANDY_TALISMAN', 'CANDY_RING'],
        INTIMIDATION_ARTIFACT: ['INTIMIDATION_TALISMAN', 'INTIMIDATION_RING'], 
        SPIDER_ARTIFACT: ['SPIDER_TALISMAN', 'SPIDER_RING'],
        RED_CLAW_ARTIFACT: ['RED_CLAW_TALISMAN', 'RED_CLAW_RING'],
        HUNTER_RING: ['HUNTER_TALISMAN'],
        ZOMBIE_ARTIFACT: ['ZOMBIE_TALISMAN', 'ZOMBIE_RING'],
        BAT_ARTIFACT: ['BAT_TALISMAN', 'BAT_RING'],
        SEAL_OF_THE_FAMILY: ['SHADY_RING', 'CROOKED_ARTIFACT'],
        WOLF_RING: ['WOLF_TALISMAN']
    }
}